### PR TITLE
feat: Experts on twitter, more articles, movies and podcast

### PR DESCRIPTION
**Pull request by roboflank**

### CODE REVIEW

**Comment by freeman42x** [comment]
Thank you for your contribution. I will merge it as soon as I get some free time to review it.

**Comment by roboflank** [comment]
Awesome.

**Comment by freeman42x** [comment]
@wamburu https://twimlai.com/ does not seem to be AGI specific so I removed it, correct me if I am wrong.
Everything else looks good. Thank you very much for your contribution!

**Comment by roboflank** [comment]
@wamburu  yes, my bad. Though there are some specific topics on AGI.
Thanks for the merge 🎉

**Pull request merged**
